### PR TITLE
Correct `RemoteDataT3` constraint for `M` (`URIS4` -> `URIS3`)

### PR DESCRIPTION
**Pull request by OliverJAsh**
This was giving me errors, it looks incorrect—this should fix it.

### CODE REVIEW

**Comment by Magellol** [comment]
Possible to get this merged so we can remove the patch on our end? Thank you!

**Review by evgeniy-ugryumov — APPROVED** [review]

**Comment by sutarmin** [comment]
Thanks for your contribution and sorry for the delay 😅

**Comment by OliverJAsh** [comment]
No problem! Would you be able to do a quick patch release?

**Comment by sutarmin** [comment]
Sure. [2.0.5](https://www.npmjs.com/package/@devexperts/remote-data-ts/v/2.0.5) is out!

**Pull request merged**
