### PR TITLE
Fold 3

### LINKED ISSUE #30: Synthetic fold
hi @raveclassic,
first of all, thank you for this piece of code, it defines a very complete and clean interface for dealing with IO data.

In most of the apps I design, when I fetch data the `initial` case does not need to be handled (data is fetched as soon as a view is loaded so I want to handle only the `loading`, `failure` and `success` cases). As this is true for 95% of my use cases, it seems a bit overkill to `fold` on my data structures as it forces me to handle separately the `loading` and `initial` case but at the same time, I would like to keep the strictness for all other cases.
How would you feel about a `syntheticFold` method that merges the handling of `initial` and `loading`?

### PR DESCRIPTION
**Pull request by fes300**
close #30 

add `fold3` utility

### CODE REVIEW

**Comment by fes300** [comment]
@raveclassic do you think this addition is legit or should I just add it in my codebase?

**Comment by raveclassic** [comment]
Hi @fes300, thanks for the PR!

I am very sorry for such a late response :(

The PR LGTM but there's one thing - could you please revert the changelog? It's generated on publish.

**Review by raveclassic — CHANGES_REQUESTED** [review]
Please revert changelog.md

**Comment by fes300** [comment]
Hi @raveclassic no problem, I deleted the changelog 👍 
merry Christmas! 🎅

**Review by raveclassic — APPROVED** [review]

**Pull request merged**
