### PR TITLE
Provide version with ES modules

### PR DESCRIPTION
**Pull request by OliverJAsh**
Fixes https://github.com/devexperts/remote-data-ts/issues/41

I copied what fp-ts does.

### CODE REVIEW

**Comment by raveclassic** [comment]
Awesome, thanks!
One small thing. As you can see, we've moved from old `devex-web-frontend` to `devexperts` namespace which now requires contributors to [sign Contributor License Agreement](https://cla.devexperts.com/devexperts/remote-data-ts?pullRequest=42).

**Comment by OliverJAsh** [comment]
Done!

**Comment by OliverJAsh** [comment]
Thanks, could you let me know when this is released?

**Comment by raveclassic** [comment]
Done! I released a patch `2.0.1`

**Comment by OliverJAsh** [comment]
Note that importing the main module still causes all of io-ts to be imported. IICU, that's because io-ts-types does not yet support tree shaking. PR here: https://github.com/gcanti/io-ts-types/pull/118.

**Pull request merged**
